apiVersion: apps/v1
kind: Deployment
metadata:
  name: test5
  labels:
    app: test5
  namespace: namespace-workflow-1678903240111
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test5
  template:
    metadata:
      labels:
        app: test5
    spec:
      containers:
        - name: test5
          image: acrworkflow1678903240111.azurecr.io/image-workflow-1678903240111:latest
          ports:
            - containerPort: 800