apiVersion: apps/v1
kind: Deployment
metadata:
  name: davidgamero-test6
  labels:
    app: davidgamero-test6
  namespace: namespace-workflow-1678824331072
spec:
  replicas: 1
  selector:
    matchLabels:
      app: davidgamero-test6
  template:
    metadata:
      labels:
        app: davidgamero-test6
    spec:
      containers:
        - name: davidgamero-test6
          image: acrworkflow1678824331072.azurecr.io/image-workflow-1678824331072:latest
          ports:
            - containerPort: 8000