apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-test
  labels:
    app: rust-test
  namespace: namespace-workflow-1678734092643
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-test
  template:
    metadata:
      labels:
        app: rust-test
    spec:
      containers:
        - name: rust-test
          image: acrworkflow1678734092643.azurecr.io/image-workflow-1678734092643:latest
          ports:
            - containerPort: 8000