apiVersion: apps/v1
kind: Deployment
metadata:
  name: erin
  labels:
    app: erin
  namespace: namespace-workflow-1678743903656
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erin
  template:
    metadata:
      labels:
        app: erin
    spec:
      containers:
        - name: erin
          image: acrworkflow1678743903656.azurecr.io/image-workflow-1678743903656:latest
          ports:
            - containerPort: 8000